/**
 * This file was generated by farrow-api
 * Don't modify it manually
 */

import { createApiPipelineWithUrl, ApiInvokeOptions } from 'farrow-api-client'

/**
 * {@label BoId}
 */
export type BoId = {
  /**
   * @remarks Todo id
   */
  id: number
}

/**
 * {@label AddBookInput}
 */
export type AddBookInput = {
  /**
   * @remarks Pet object that needs to be added to the store
   */
  body: IBook
}

/**
 * {@label IBook}
 */
export type IBook = {
  name: string
  description: string
}

/**
 * {@label InvalidInput}
 */
export type InvalidInput = {
  type: 'InvalidInput'
}

/**
 * {@label AddBookOutput}
 */
export type AddBookOutput = {
  type: 'AddPetOutput'
  book: IBook
}

export const url = 'http://localhost:3000/book'

export const apiPipeline = createApiPipelineWithUrl(url)

export const api = {
  /**
   * @remarks remove todo
   */
  getList: (input: BoId, options?: ApiInvokeOptions) =>
    apiPipeline.invoke({ type: 'Single', path: ['getList'], input }, options) as Promise<any>,
  /**
   * @remarks add a book
   */
  AddBook: (input: AddBookInput, options?: ApiInvokeOptions) =>
    apiPipeline.invoke({ type: 'Single', path: ['AddBook'], input }, options) as Promise<InvalidInput | AddBookOutput>,
}
